return {
	Apple = {
		HarvestTime = 1,
		RespawnTime = 10,
		Value = 2,
		FruitSpawnType = "UnderTreeStick",
		FruitsPerSpawn = 2,
		Weight = { 140, 200 },
	},
	Watermelon = {
		HarvestTime = 3,
		RespawnTime = 45,
		Value = 0.5,
		FruitSpawnType = "RopeConnected",
		FruitsPerSpawn = { 2, 5 },
		Weight = { 3000, 6500 },
	},
	Pear = {
		HarvestTime = 2,
		RespawnTime = 20,
		Value = 3,
		FruitSpawnType = "UnderTreeStick",
		FruitsPerSpawn = 1,
		Weight = { 150, 220 },
	},
	Banana = {
		HarvestTime = 1.5,
		RespawnTime = 15,
		Value = 1.5,
		FruitSpawnType = "Berrie",
		FruitsPerSpawn = 3,
		Weight = { 100, 150 },
	},
	Strawberry = {
		HarvestTime = 0.4,
		RespawnTime = 30,
		Value = 6,
		FruitSpawnType = "Berrie",
		FruitsPerSpawn = 1,
		Weight = { 9, 14 },
	},
	Blueberry = {
		HarvestTime = 0.1,
		RespawnTime = 30,
		Value = 12,
		FruitSpawnType = "Berrie",
		FruitsPerSpawn = 1,
		Weight = { 1, 5 },
	},
}
