return function()
	local TreeService = require(game.ServerStorage.Source.Services.TreeService)

	describe("CreateTree", function()
		it("should return tree model", function()
			local tree: Model = TreeService.CreateTree("Apple")
			expect(tree).to.be.ok()
			expect(typeof(tree)).to.equal("Instance")
			expect(tree:IsA("Model")).to.equal(true)
		end)
	end)

	describe("PositionTreeOnPart", function()
		it("should position a tree on part", function()
			local tree: Model = TreeService.CreateTree("Apple")
			local part: Part = Instance.new("Part")
			expect(function()
				TreeService.PositionTreeOnPart(tree, part)
			end).to.never.throw()
		end)
	end)

	describe("ParentTreeToHolder", function()
		it("should parent tree to holder", function()
			local tree: Model = TreeService.CreateTree("Apple")
			expect(function()
				TreeService.ParentTreeToHolder(tree)
			end).to.never.throw()
			tree:Destroy()
		end)
	end)
end
